### ISSUE TITLE
Question: Is this a fork or just a rebuild ?

### ISSUE THREAD

**Issue by ddscentral** [satgit62/pvr.hts-tvhead-client-on-LG-webOS#4]
The inputstream.ffmpegdirect plugin is GPL licensed, yet I only see binaries in this repository without source code.

Is this version a fork or just a recompilation of existing sources with WebOS ARM toolchain ?

**Comment by satgit62** [comment]
Hello,
Sorry for the misunderstanding about the license, this is just a recompile of the existing sources with the WebOS ARM toolchain. Since the source of the binary add-ons is under GNU GENERAL PUBLIC LICENSE version 2 and not version 3, I have now changed it to version 2.
See: https://github.com/xbmc/xbmc/blob/master/docs/README.webOS.md#72-add-binary-addons-to-project
Source: https://github.com/xbmc/repo-binary-addons

**Comment by ddscentral** [comment]
Thanks for clarifying. Just wanted to know if I this is a fork or not, in case if I need to do a rebuild myself.

And thanks for this build, it works well on my LG C1, fixed the live stream stuttering issue in Kodi.
